### ISSUE TITLE
Add instructions to fix PATH so that anaconda is not used.

### ISSUE THREAD

**Issue by srisi** [dhmit/urop#7] opened 2019-09-09 14:37 UTC
Involves either commenting out anaconda instructions in .bash_profile (Mac) or changing settings -> ?Environment variables (for user only)? on Windows

**Comment by ryaanahmed** [comment] 2019-09-09 14:45
> Environment variables (for user only)
Can also by system env variables if the user installed Anaconda (or an earlier version of Python) as a system-level install rather than a user-level install. (putting this here to remind me, as we encountered this also with one student)

**Comment by ryaanahmed** [comment] 2021-08-30 16:49
dupe of #22

**Closed by ryaanahmed** 2021-08-30 16:49 UTC
